Provide default for gui popup response to avoid exception
Code currently throws:

Traceback (most recent call last):
  File "C:\neurobooth-os\neurobooth_os\gui.py", line 611, in main
    gui()
  File "C:\neurobooth-os\neurobooth_os\gui.py", line 487, in gui
    _pause_tasks(steps, presentation_node=nodes[1])
  File "C:\neurobooth-os\neurobooth_os\gui.py", line 202, in _pause_tasks
    socket_message(resp.lower(), presentation_node)
AttributeError: 'NoneType' object has no attribute 'lower'

because closing the popup by clicking the x button causes it to return None.